# Generated by Django 3.1.4 on 2020-12-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DukeLester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=45)),
                ('Middle_name', models.CharField(max_length=45)),
                ('Last_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('profile_photo', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
